<?php

namespace App\Imports;

use App\Models\customer;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class CustomerImport implements ToModel,WithHeadingRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new customer([
            'first_name', => $row['first_name']
            'last_name', => $row['last_name']
            'email', => $row['email']
            'phone_number', => $row['phone_number']
            'address', => $row['address']
            'date_of_birth', => $row['date_of_birth']
            'gender', => $row['gender']
            'cnic', => $row['cnic']
            'image', => $row['image']
            'current_activity_level', => $row['current_activity_level']
            'daily_routine', => $row['daily_routine']
            'medical_condition', => $row['medical_condition']
            'medical_condition_description', => $row['medical_condition_description']
            'prev_injury', => $row['prev_injury']
            'previous_excersice', => $row['previous_excersice']
            'daily_diet', => $row['daily_diet']
            'test1_core_activation', => $row['test1_core_activation']
            'test1_core_activation_description', => $row['test1_core_activation_description']
            'test2_core_activation', => $row['test2_core_activation']
            'test2_core_activation_description', => $row['test2_core_activation_description']
            'strength_core_activation', => $row['strength_core_activation']
            'strength_core_activation_description', => $row['strength_core_activation_description']
            'test_glute_activation', => $row['test_glute_activation']
            'test_glute_activation_description', => $row['test_glute_activation_description']
            'strength_glute_activation', => $row['strength_glute_activation']
            'strength_glute_activation_description', => $row['strength_glute_activation_description']
            'test_clamshells_activation', => $row['test_clamshells_activation']
            'test_clamshells_activation_description', => $row['test_clamshells_activation_description']
            'strength_clamshells_activation', => $row['strength_clamshells_activation']
            'strength_clamshells_activation_description', => $row['strength_clamshells_activation_description']
            'measurement_cal_unit', => $row['measurement_cal_unit']
            'chest', => $row['chest']
            'waist', => $row['waist']
            'hips', => $row['hips']
            'weight_cal_unit', => $row['weight_cal_unit']
            'body_weight', => $row['body_weight']
            'body_fat', => $row['body_fat']
            'muscles_mass', => $row['muscles_mass']
            'squat_test_1', => $row['squat_test_1']
            'squat_test_1_desc', => $row['squat_test_1_desc']
            'squat_test_2', => $row['squat_test_2']
            'squat_test_2_desc', => $row['squat_test_2_desc']
            'squat_test_3', => $row['squat_test_3']
            'squat_test_3_desc', => $row['squat_test_3_desc']
            'squat_test_4', => $row['squat_test_4']
            'squat_test_4_desc', => $row['squat_test_4_desc']
            'squat_test_5', => $row['squat_test_5']
            'squat_test_5_desc', => $row['squat_test_5_desc']
            'squat_test_6', => $row['squat_test_6']
            'squat_test_6_desc', => $row['squat_test_6_desc']
            'squat_test_7', => $row['squat_test_7']
            'squat_test_7_desc', => $row['squat_test_7_desc']
            'squat_test_8', => $row['squat_test_8']
            'squat_test_8_desc', => $row['squat_test_8_desc']
            'squat_test_9', => $row['squat_test_9']
            'squat_test_9_desc', => $row['squat_test_9_desc']
            'strength_squat_activation', => $row['strength_squat_activation']
            'strength_squat_activation_description', => $row['strength_squat_activation_description']
            'date_of_joining', => $row['date_of_joining']
            'month_end', => $row['month_end']
            'renew_joining', => $row['renew_joining']
            'renew_month_end', => $row['renew_month_end']
            'training_type', => $row['training_type']
            'trainer_name', => $row['trainer_name']
            'status', => $row['status']
            'fees_clear', => $row['fees_clear']
            'reference_name', => $row['reference_name']
            'registration_fees', => $row['registration_fees']
            'gym_fees', => $row['gym_fees']
            'trainer_fees_per_session', => $row['trainer_fees_per_session']
            'total_session', => $row['total_session']
            'advnace_allow', => $row['advnace_allow']
            'advance_month', => $row['advance_month']
            'discount', => $row['discount']
            'avance_total', => $row['avance_total']
            'mon_start_time', => $row['mon_start_time']
            'mon_end_time', => $row['mon_end_time']
            'mon_allow_pt', => $row['mon_allow_pt']
            'tue_start_time', => $row['tue_start_time']
            'tue_end_time', => $row['tue_end_time']
            'tue_allow_pt', => $row['tue_allow_pt']
            'wed_start_time', => $row['wed_start_time']
            'wed_end_time', => $row['wed_end_time']
            'wed_allow_pt', => $row['wed_allow_pt']
            'thu_start_time', => $row['thu_start_time']
            'thu_end_time', => $row['thu_end_time']
            'thu_allow_pt', => $row['thu_allow_pt']
            'fri_start_time', => $row['fri_start_time']
            'fri_end_time', => $row['fri_end_time']
            'fri_allow_pt', => $row['fri_allow_pt']
            'sat_start_time', => $row['sat_start_time']
            'sat_end_time', => $row['sat_end_time']
            'sat_allow_pt', => $row['sat_allow_pt']
            'sun_start_time', => $row['sun_start_time']
            'sun_end_time', => $row['sun_end_time'],
            'sun_allow_pt', => $row['sun_allow_pt']
        ]);
    }
}
